blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/AV-Foundry/VideoTuner/discussions
    about: For questions or general discussion, please use GitHub Discussions instead of opening an issue.
